# Generated by Django 5.1.3 on 2024-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0022_rename_payment_method_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='Web.product'),
        ),
    ]
