# Generated by Django 5.1.3 on 2024-12-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0024_manager_user_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user_ptr',
        ),
    ]
