# Generated by Django 5.1.3 on 2024-12-10 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0025_remove_manager_user_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Children',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Children',
                'verbose_name_plural': 'User_Children',
                'db_table': 'user_children',
            },
            bases=('Web.user',),
        ),
    ]
