# Generated by Django 5.1.3 on 2024-12-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0026_user_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_children',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
