# Generated by Django 5.1.3 on 2024-12-10 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0027_user_children_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Children',
        ),
    ]
