# Generated by Django 5.1.3 on 2024-12-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0029_alter_paymentmethod_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham', to='Web.product')),
            ],
        ),
    ]
