# Generated by Django 5.1.3 on 2024-12-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0030_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
