# Generated by Django 5.1.3 on 2024-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0031_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
