# Generated by Django 5.1.3 on 2024-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0033_alter_orderitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
