# Generated by Django 5.1.3 on 2024-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0034_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='zalo_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
