# Generated by Django 5.1.3 on 2024-12-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0035_businessinfo_zalo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='zalo_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
