# Generated by Django 5.1.3 on 2024-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0036_alter_businessinfo_zalo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='Web.product'),
        ),
    ]
