# Generated by Django 5.1.3 on 2024-12-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0037_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='methodname',
            field=models.CharField(choices=[('COD', 'COD'), ('QRPay', 'QRPay')], default='COD', max_length=20),
        ),
    ]
